import Phaser from 'phaser';
import { soundManager } from '../systems/SoundManager.js';
import { GamepadNav } from '../systems/GamepadNav.js';

export default class CreditsScene extends Phaser.Scene {
    constructor() { super('CreditsScene'); }

    create() {
        const w = this.scale.width, h = this.scale.height;

        this.add.rectangle(0, 0, w, h, 0x000000).setOrigin(0);
        for (let i = 0; i < 60; i++) {
            this.add.rectangle(
                Phaser.Math.Between(0, w), Phaser.Math.Between(0, h),
                Math.random() < 0.3 ? 2 : 1, Math.random() < 0.3 ? 2 : 1,
                0xffffff, Math.random() * 0.45 + 0.1
            );
        }

        // Fixed title area (never scrolls)
        this.add.text(w / 2, 26, 'CREDITS', {
            font: 'bold 18px monospace', fill: '#ffd700',
            stroke: '#886600', strokeThickness: 2,
        }).setOrigin(0.5);
        this.add.rectangle(w / 2, 42, 200, 1, 0x332200).setOrigin(0.5);

        // Scrollable content container
        const CONT_Y = 50;
        this._scrollY = 0;
        this._cont = this.add.container(0, CONT_Y);

        const _sec  = (cy, text, fill = '#cc99ff') =>
            this._cont.add(this.add.text(w / 2, cy, text, { font: 'bold 8px monospace', fill }).setOrigin(0.5));
        const _body = (cy, text, fill = '#665577') =>
            this._cont.add(this.add.text(w / 2, cy, text, { font: '8px monospace', fill }).setOrigin(0.5));
        const _sep  = (cy) =>
            this._cont.add(this.add.rectangle(w / 2, cy, 160, 1, 0x221133).setOrigin(0.5));

        // ── Game ─────────────────────────────────────────────────
        _sec(8,  'ARCANE MAJESTY — Prologue: The Forest Hunt');
        _body(20, 'A concept-album RPG universe', '#554466');
        _sep(34);

        // ── AI generation note ────────────────────────────────────
        _sec(45, 'GENERATED BY AI', '#9966cc');
        const aiLine = [
            'This project was built entirely through AI-assisted',
            'development using Claude, Gemini, GitHub Copilot,',
            'ChatGPT, and multiple local LLM models running on',
            'OpenWebUI — all supervised and directed by',
        ];
        aiLine.forEach((line, i) => _body(60 + i * 11, line));
        _body(60 + aiLine.length * 11, 'Étienne Gagné Nadeau', '#ddbbff');
        _sep(132);

        // ── Special thanks ────────────────────────────────────────
        _sec(141, 'SPECIAL THANKS');
        _body(155, 'Thomas Gagné');
        _body(166, 'Support & creative content contribution', '#443355');
        _sep(182);

        // ── Tech stack ────────────────────────────────────────────
        _sec(190, 'TECHNOLOGY');
        _body(203, 'Phaser 3  ·  Vite  ·  WebAudio API');
        _body(213, 'Pipoya RPG sprite assets');

        this._contentH = 228;

        // Fixed back button
        const backBtn = this.add.text(w / 2, h - 18, '← Back to Menu', {
            font: '10px monospace', fill: '#7755aa',
        }).setOrigin(0.5).setInteractive({ useHandCursor: true });
        backBtn.on('pointerover', () => backBtn.setStyle({ fill: '#ffffff' }));
        backBtn.on('pointerout',  () => backBtn.setStyle({ fill: '#7755aa' }));
        backBtn.on('pointerdown', () => this._back());

        // Touch scroll
        const AVAIL = h - CONT_Y - 30;
        let _touchY = null;
        this.input.on('pointerdown', ptr => { _touchY = ptr.y; });
        this.input.on('pointermove', ptr => {
            if (_touchY === null || !ptr.isDown) return;
            const dy = _touchY - ptr.y;
            _touchY = ptr.y;
            const max = Math.max(0, this._contentH - AVAIL);
            this._scrollY = Phaser.Math.Clamp(this._scrollY + dy, 0, max);
            this._cont.y = CONT_Y - this._scrollY;
        });
        this.input.on('pointerup', () => { _touchY = null; });

        this.input.keyboard.on('keydown-ESC', () => this._back());
        this._gpNav = new GamepadNav(this);
        this.cameras.main.fadeIn(300);
    }

    update(time, delta) {
        const gp = this._gpNav.poll(delta);
        if (!gp) return;
        if (gp.B || gp.A) this._back();
        const CONT_Y = 50;
        const max = Math.max(0, this._contentH - (this.scale.height - CONT_Y - 30));
        if (gp.up)   { this._scrollY = Math.max(0,   this._scrollY - 16); this._cont.y = CONT_Y - this._scrollY; }
        if (gp.down) { this._scrollY = Math.min(max,  this._scrollY + 16); this._cont.y = CONT_Y - this._scrollY; }
    }

    _back() {
        soundManager.menuHover();
        this.cameras.main.fadeOut(200);
        this.time.delayedCall(200, () => this.scene.start('MenuScene'));
    }
}
