import Phaser from 'phaser';
import { soundManager } from '../systems/SoundManager.js';
import { GamepadNav } from '../systems/GamepadNav.js';

export default class CreditsScene extends Phaser.Scene {
    constructor() { super('CreditsScene'); }

    create() {
        const w = this.scale.width, h = this.scale.height;

        this.add.rectangle(0, 0, w, h, 0x000000).setOrigin(0);
        for (let i = 0; i < 60; i++) {
            this.add.rectangle(
                Phaser.Math.Between(0, w), Phaser.Math.Between(0, h),
                Math.random() < 0.3 ? 2 : 1, Math.random() < 0.3 ? 2 : 1,
                0xffffff, Math.random() * 0.45 + 0.1
            );
        }

        // Title
        this.add.text(w / 2, 26, 'CREDITS', {
            font: 'bold 18px monospace', fill: '#ffd700',
            stroke: '#886600', strokeThickness: 2,
        }).setOrigin(0.5);
        this.add.rectangle(w / 2, 42, 200, 1, 0x332200).setOrigin(0.5);

        // ── Game ─────────────────────────────────────────────────
        this._section(w / 2, 58, 'ARCANE MAJESTY — Prologue: The Forest Hunt');
        this._section(w / 2, 70, 'A concept-album RPG universe', '#554466');

        this.add.rectangle(w / 2, 84, 160, 1, 0x221133).setOrigin(0.5);

        // ── AI generation note ────────────────────────────────────
        this._section(w / 2, 95, 'GENERATED BY AI', '#9966cc');

        const aiLine = [
            'This project was built entirely through AI-assisted',
            'development using Claude, Gemini, GitHub Copilot,',
            'ChatGPT, and multiple local LLM models running on',
            'OpenWebUI — all supervised and directed by',
        ];
        aiLine.forEach((line, i) => this._body(w / 2, 110 + i * 11, line));
        this._body(w / 2, 110 + aiLine.length * 11, 'Étienne Gagné Nadeau', '#ddbbff');

        this.add.rectangle(w / 2, 182, 160, 1, 0x221133).setOrigin(0.5);

        // ── Special thanks ────────────────────────────────────────
        this._section(w / 2, 191, 'SPECIAL THANKS');
        this._body(w / 2, 205, 'Thomas Gagné');
        this._body(w / 2, 216, 'Support & creative content contribution', '#443355');

        this.add.rectangle(w / 2, 232, 160, 1, 0x221133).setOrigin(0.5);

        // ── Tech stack ────────────────────────────────────────────
        this._section(w / 2, 240, 'TECHNOLOGY');
        this._body(w / 2, 253, 'Phaser 3  ·  Vite  ·  WebAudio API');
        this._body(w / 2, 263, 'Pipoya RPG sprite assets');

        // ── Back ──────────────────────────────────────────────────
        const backBtn = this.add.text(w / 2, h - 18, '← Back to Menu', {
            font: '10px monospace', fill: '#7755aa',
        }).setOrigin(0.5).setInteractive({ useHandCursor: true });
        backBtn.on('pointerover', () => backBtn.setStyle({ fill: '#ffffff' }));
        backBtn.on('pointerout',  () => backBtn.setStyle({ fill: '#7755aa' }));
        backBtn.on('pointerdown', () => this._back());

        this.input.keyboard.on('keydown-ESC', () => this._back());
        this._gpNav = new GamepadNav(this);
        this.cameras.main.fadeIn(300);
    }

    update(time, delta) {
        const gp = this._gpNav.poll(delta);
        if (!gp) return;
        if (gp.B || gp.A) this._back();
    }

    _section(x, y, text, fill = '#cc99ff') {
        this.add.text(x, y, text, {
            font: 'bold 8px monospace', fill,
        }).setOrigin(0.5);
    }

    _body(x, y, text, fill = '#665577') {
        this.add.text(x, y, text, {
            font: '8px monospace', fill,
        }).setOrigin(0.5);
    }

    _back() {
        soundManager.menuHover();
        this.cameras.main.fadeOut(200);
        this.time.delayedCall(200, () => this.scene.start('MenuScene'));
    }
}
